@startuml
actor  Actor as Actor
Actor -> ManagerPage : User click "Sự kiện" on the menu
activate ManagerPage
ManagerPage -> AdminCampaignControllerImpl : adminGetAll
activate AdminCampaignControllerImpl
AdminCampaignControllerImpl -> CampaignService : adminGetAll
activate CampaignService
CampaignService -> CampaignServiceImpl : adminGetAll
activate CampaignServiceImpl
CampaignServiceImpl -> CampaignRepos : findByBannerContainsIgnoreCase
activate CampaignRepos
CampaignRepos --> CampaignServiceImpl
deactivate CampaignRepos
CampaignServiceImpl -> AdminCampaignDtoOut : builder
activate AdminCampaignDtoOut
AdminCampaignDtoOut -> AdminCampaignDtoOutBuilder : new
activate AdminCampaignDtoOutBuilder
AdminCampaignDtoOutBuilder --> AdminCampaignDtoOut
deactivate AdminCampaignDtoOutBuilder
AdminCampaignDtoOut --> CampaignServiceImpl
deactivate AdminCampaignDtoOut
CampaignServiceImpl -> AdminCampaignDtoOutBuilder : build
activate AdminCampaignDtoOutBuilder
AdminCampaignDtoOutBuilder -> AdminCampaignDtoOut : new
activate AdminCampaignDtoOut
AdminCampaignDtoOut --> AdminCampaignDtoOutBuilder
deactivate AdminCampaignDtoOut
AdminCampaignDtoOutBuilder --> CampaignServiceImpl
deactivate AdminCampaignDtoOutBuilder
CampaignServiceImpl --> CampaignService
deactivate CampaignServiceImpl
CampaignService --> AdminCampaignControllerImpl
deactivate CampaignService
return
@enduml