@startuml
'https://plantuml.com/object-diagram

package fpt.custome.yourlure{
package fpt.custome.yourlure.controller{
package fpt.custome.yourlure.controller.admin{
class AdminCampaignController{
  ResponseEntity<Object> adminGetAll(@RequestBody AdminFilterDtoInput adminFilterDtoInput);

}
}
}
}
@enduml
