# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI

on:
  push:
    branches: [ MAIN-BACKEND ]
  pull_request:
    branches: [ MAIN-BACKEND ]

jobs:
  build:
    runs-on: backend

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      - name: Build with Maven
      - run: mvn package
      - run: cd target/
      - run: java -jar yourlure-0.0.1-SNAPSHOT.jar
